### ISSUE TITLE
Unrecognized option "pagination" under "controller_extra"

### ISSUE THREAD

**Issue by danaki** [mmoreram/ControllerExtraBundle#58]
Just copy and paste default config
```
controller_extra:
    resolver_priority: -8
    request: current
    factory:
        default_method: create
        default_static: true
    pagination:
        active: true
        default_name: paginator
        default_page: 1
        default_limit_per_page: 10
    entity:
        active: true
        default_name: entity
        default_persist: true
        default_mapping_fallback: false
    form:
        active: true
        default_name: form
    object_manager:
        active: true
        default_name: form
    flush:
        active: true
        default_manager: default
    json_response:
        active: true
        default_status: 200
        default_headers: []
    log:
        active: true
        default_level: info
        default_execute: pre
```

from documentation.
